### ISSUE TITLE
Directory rename issue

### ISSUE THREAD

**Issue by submediax** [fabriceci/RichFilemanager-JAVA#3]
Hey there!

There is problem with directory rename, it doesn't work.

I would suggest to amend the following change into _com.fabriceci.fmc.impl.LocalFileManager#actionRename_ to fix it:

<img width="624" alt="screenshot1" src="https://user-images.githubusercontent.com/37540715/37895707-cab66852-30ea-11e8-82ae-8af7faa40c07.png">

**Comment by fabriceci** [comment]
Indeed, I added a comment to the method to not forget to test, but it seems I forget it at the end.

Thanks, fixed in 2246360e27bc9bb4c41d3aa8f16a9cbc6f94982e
