### ISSUE TITLE
Wrong filenames for nonlatin names when download

### ISSUE THREAD

**Issue by submediax** [fabriceci/RichFilemanager-JAVA#4]
When downloading e.g. cyrillic / greek named files, filename substitutes with underscores.
We could fix it by adding a few lines in _com.fabriceci.fmc.impl.LocalFileManager#actionDownload_:

<img width="995" alt="screenshot2" src="https://user-images.githubusercontent.com/37540715/37896029-8d120208-30eb-11e8-9202-a94732b9aefb.png">

**Comment by fabriceci** [comment]
Thank you for your contribution, don't hesitate to make a PR directly next time.

Fixed in 6207124cf5135e884b9cfcd47eacfe0fe6d430fc
