### ISSUE TITLE
Data encryption

### ISSUE THREAD

**Issue by submediax** [fabriceci/RichFilemanager-JAVA#6]
Hi fabriceci!

Let me propose an implementation of a new feature for data encryption / decryption.

It would be good to have the functionality, for example for the cases when sensitive data stored on cloud where users could lost access thus to protect data from third-party...

I'll take care about it in closest future so would like to hear your thoughts.

Thanks

**Comment by fabriceci** [comment]
Hi @submediax,

Could you explain how you intend to implement this? 

Does the change do it require to edit the client side script?

**Comment by submediax** [comment]
Hey there,

The change won't require on client side big changes. I'm going to modify only server side for now. In a few words, before writing anything to disk - encrypt it. After reading from disk - decrypt before returning to client.

Encryption will probably break file previews for e.g. images etc. so I need to think how to proceed with: either leave it as is or substitute file preview icon depending on file type plus some specific mark onto icon to indicate that a file is encrypted. It might entail minor client changes, will see.

**Comment by fabriceci** [comment]
Where do you want to store the password to make encryption/decryption?

Because if the goal is to prevent the server users (e.g. the provider company) to read encrypted files, and the password is written on a config file. It’s easy for anyone to read the code and decrypt files. Am I wrong?

**Comment by submediax** [comment]
Password will be generated dynamically & specific to logged in user from within the web app

**Comment by fabriceci** [comment]
OK I see, it will be a simple property passed dynamically to the instance. (I suppose you will use crypto.Cipher with AES)

**Comment by fabriceci** [comment]
I close the issue, don't hesitate to reopen it if you have any news about it.
