### ISSUE TITLE
Migration to maven

### ISSUE THREAD

**Issue by curiousPup** [fabriceci/RichFilemanager-JAVA#7]
Is this project supported as a maven project as well?
I tried converting it to maven but got the following error

Could not resolve dependencies for project com.fabriceci.fmc:fmconnector:jar:1.0-SNAPSHOT

**Comment by kienhaw** [comment]
You shouldn't convert it to maven project, just import the fmc into your project will do. 
Please refer to the project structure below for better understanding.

![image](https://user-images.githubusercontent.com/32449757/40771532-27c5d3a0-64f0-11e8-8bd6-73a555a241ef.png)

**Comment by curiousPup** [comment]
but the project I want to integration this into is a maven project

**Comment by kienhaw** [comment]
My project was built using maven too. 
I would suggest you to try to import the FMC into your maven project first.

**Comment by fabriceci** [comment]
I don't use Maven, @kienhaw seems to be able to help. however, I know it's simple to generate a pom file with the grade plugin maven. I don't know if that can help.
