### ISSUE TITLE
Unable to upload files using java

### ISSUE THREAD

**Issue by u4bharat** [fabriceci/RichFilemanager-JAVA#8]
- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x]  I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ ] PHP connector by **servocoder**
- [x] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [ ] ASP.NET Core connector by **sinanbozkus**
- [ ] ASHX connector by **richeflits**
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

I'm Using Rich file manager in my web application but I'm not upload any files in it.
The version which i'm using for rich file manager is 2.5.1. The web app is developed in Spring MVC.
However, even if I hover my mouse on it, no information shows, only a red, blank dialog.
All other functions are working properly, that are, folder and files retrieval, and file downloads.
![dsaasd](https://user-images.githubusercontent.com/45810697/49849684-c6966400-fe00-11e8-85fb-2b47f8de235d.png)
And chrome console gives the following error:
![image](https://user-images.githubusercontent.com/45810697/49849777-2260ed00-fe01-11e8-8b2a-8d5da8cf2a02.png)

Any help would be greatly appreciated. Thanks in advance.

**Comment by fabriceci** [comment]
Closed for double post : [here](https://github.com/servocoder/RichFilemanager/issues/364)
